// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdorymrvnmtjmflsrcgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpkb3J5bXJ2bm10am1mbHNyY2dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMjI3NTIsImV4cCI6MjA2OTY5ODc1Mn0.YRSm0CuEKjhWOUYEUDt1yTrqvq9qG0_X7zRbtjccQ60";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});